#!/bin/bash
#SBATCH --job-name=comm20_hyp_vqvae
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=24:00:00
#SBATCH --output=outputs/comm20_hyp_vqvae%j.out
#SBATCH --error=outputs/comm20_hyp_vqvae%j.err

# 1. Environment
module load 2024
module load Miniconda3/24.7.1-0
module load Mamba/24.9.0-0
source activate ~/.conda/envs/ggball
export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/src/models/hyperbolic_nn_plusplus

# 2. WandB Setup
export WANDB_START_METHOD=thread
export WANDB_SILENT=true
if [ -f "wandb.key" ]; then
    export WANDB_API_KEY=$(cat wandb.key)
    export WANDB_MODE=online
    WANDB_LOG_MODE=online
    echo "WandB API key loaded from wandb.key"
elif [ -n "$WANDB_API_KEY" ]; then
    export WANDB_MODE=online
    WANDB_LOG_MODE=online
    echo "WandB API key found in environment"
else
    export WANDB_MODE=offline
    WANDB_LOG_MODE=offline
    echo "No WandB API key found. Using offline mode."
fi

CURVATURE=$1
echo "Using curvature ${CURVATURE}"

# 3. Execution
time ~/.conda/envs/ggball/bin/python3 src/main.py \
  +experiment=comm20_hyp \
  dataset=comm20 \
  loss=VQVAE \
  model.c=${CURVATURE} \
  general.wandb=${WANDB_LOG_MODE} \
  dataset.debug=false \
  loss.codebook_size=32 \
  model.hyp_channels=64 \
  model.latent_channels=64 \
  model.euc_channels=0 \
  loss.lambda_commitment_weight=1 \
  loss.lambda_orthogonal_reg_weight=0.1 \
  loss.lambda_vq_loss_weight=0.25 \
  loss.use_riemannian_optimizer=True \
  model.use_resnet=True \
  model.use_layernorm=False \
  model.sample_codebook_temp=None \
  train.n_epochs=130000 \
  train.lr_scheduler.T_max=130000