#!/bin/bash
#SBATCH --job-name=ego_small_hyp_vqvae
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=03:00:00
#SBATCH --output=outputs/test_ego_small_hyp_vqvae%j.out
#SBATCH --error=outputs/test_ego_small_hyp_vqvae%j.err

# 1. Environment
module purge
module load 2024
module load Miniconda3/24.7.1-0
module load Mamba/24.9.0-0

source activate HypeFlow
export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/src/models/hyperbolic_nn_plusplus

# 2. WandB Fixes
export WANDB_START_METHOD=thread
export WANDB_SILENT=true
export WANDB_API_KEY="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"
if [ -n "${WANDB_API_KEY}" ]; then
  export WANDB_MODE=online
  WANDB_LOG_MODE=online
  echo "WANDB_API_KEY detected: using online mode."
else
  export WANDB_MODE=offline
  WANDB_LOG_MODE=offline
  echo "WANDB_API_KEY not set: using offline mode."
fi

CURVATURE=0.1
echo "Using curvature ${CURVATURE}"

# 3. Execution
time python3 -m main \
  +experiment=ego_small_hyp \
  dataset=ego_small \
  loss=VQVAE \
  model.c=${CURVATURE} \
  general.wandb=${WANDB_LOG_MODE} \
  dataset.debug=false \
  model.hyp_channels=64 \
  model.latent_channels=64 \
  model.euc_channels=0 \
  loss.codebook_size=32 \
  loss.lambda_commitment_weight=2.0\
  loss.lambda_vq_loss_weight=0.0 \
  loss.use_riemannian_optimizer=True \
  loss.lambda_l2=0.01 \
  loss.lambda_euc2node=0 \
  loss.lambda_euc2edge=0 \
  loss.lambda_hyp2node=5 \
  loss.lambda_hyp2edge=5 \
  train.batch_size=32 \
  train.n_epochs=30000 \
  train.lr_scheduler.T_max=30000\
  loss.use_kmeans=True\
  model.sample_codebook_temp=0.1\
  loss.lambda_orthogonal_reg_weight=0.3\



# - +experiment=ego_small_hyp_copy
# - dataset=ego_small
# - loss=VQVAE
# - model.c=0.1
# - general.wandb=online
# - dataset.debug=false
# - model.hyp_channels=64
# - model.latent_channels=64
# - model.euc_channels=0
# - loss.codebook_size=32
# - loss.lambda_commitment_weight=0.75
# - loss.lambda_vq_loss_weight=1.0
# - loss.use_riemannian_optimizer=True
# - loss.lambda_l2=0.1
# - loss.lambda_euc2node=0
# - loss.lambda_euc2edge=0
# - loss.lambda_hyp2node=5
# - loss.lambda_hyp2edge=5
# - train.batch_size=32
# - train.n_epochs=30000
# - train.lr_scheduler.T_max=30000
# - loss.use_kmeans=True
