#!/bin/bash
#SBATCH --job-name=ego_small_hyp_vqvae
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=24:00:00
#SBATCH --output=outputs/ego_small_hyp_vqvae%j.out
#SBATCH --error=outputs/ego_small_hyp_vqvae%j.err

# 1. Environment
module load 2024
module load Miniconda3/24.7.1-0
module load Mamba/24.9.0-0
source activate ~/.conda/envs/ggball
export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/src/models/hyperbolic_nn_plusplus

# 2. WandB Fixes
export WANDB_START_METHOD=thread
export WANDB_SILENT=true
if [ -n "${WANDB_API_KEY}" ]; then
  export WANDB_MODE=online
  WANDB_LOG_MODE=online
  echo "WANDB_API_KEY detected: using online mode."
else
  export WANDB_MODE=offline
  WANDB_LOG_MODE=offline
  echo "WANDB_API_KEY not set: using offline mode."
fi

CURVATURE=$1
echo "Using curvature ${CURVATURE}"

# 3. Execution
time /home/scur0096/.conda/envs/ggball/bin/python3 src/main.py \
  +experiment=ego_small_hyp \
  dataset=ego_small \
  loss=AE \
  model.c=${CURVATURE} \
  general.wandb=${WANDB_LOG_MODE} \
  dataset.debug=false \
  loss.codebook_size=32 \
  model.hyp_channels=64 \
  model.latent_channels=64 \
  model.euc_channels=0 \
  loss.lambda_commitment_weight=1.0 \
  loss.lambda_orthogonal_reg_weight=0.1 \
  loss.lambda_vq_loss_weight=0.25 \
  loss.use_riemannian_optimizer=True \
  loss.lambda_l2=0.01 \
  loss.lambda_hyp2node=10 \
  loss.lambda_hyp2edge=10 \
  train.n_epochs=30000 \
  train.lr_scheduler.T_max=30000