#!/bin/bash
#SBATCH --job-name=flowmap
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=outputs/flowmap_%j.out
#SBATCH --error=outputs/flowmap_%j.err

# 1. Environment
module load 2024
module load Miniconda3/24.7.1-0
module load Mamba/24.9.0-0
source activate HypeFlow

# Assuming hypeflow is in your standard conda envs or specify full path like the reference
# If it resides in /opt/conda on your cluster, use your original target lines instead:
# source /opt/conda/bin/activate
# conda activate hypeflow

# export PYTHONPATH="$(pwd):$(pwd)/src/models/hyperbolic_nn_plusplus:$PYTHONPATH"
export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/src/models/hyperbolic_nn_plusplus
export HYDRA_FULL_ERROR=1

export WANDB_START_METHOD=thread
export WANDB_SILENT=true
export WANDB_API_KEY="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"

if [ -n "${WANDB_API_KEY}" ]; then
  export WANDB_MODE=online
  WANDB_LOG_MODE=online
  echo "WANDB_API_KEY detected: using online mode."
else
  export WANDB_MODE=offline
  WANDB_LOG_MODE=offline
  echo "WANDB_API_KEY not set: using offline mode."
fi

# 2. Arguments
# EXPERIMENT=${1:-comm20_hyp}
# DATASET=${2:-comm20}
# CHECKPOINT_PATH=${3}

# if [ -z "${CHECKPOINT_PATH}" ]; then
#   echo "Usage: sbatch $0 <experiment> <dataset> <checkpoint_path>"
#   echo "Example: sbatch $0 comm20_hyp comm20 /path/to/last.ckpt"
#   exit 1
# fi

# echo "Evaluating EXPERIMENT: ${EXPERIMENT}, DATASET: ${DATASET}"
# echo "Using Checkpoint: ${CHECKPOINT_PATH}"
# VAE_CHECKPOINT="/home/scur0096/outputs/ego_small_VQVAE_32code_hyp64_euc0_decode_pairwise_interactiondecode_c1.0-ego_small/VAE/2026-05-12/09-35-38/hypeflow-ego_small_VQVAE_32code_hyp64_euc0_decode_pairwise_interactiondecode_c1.0/aagqgkwu/checkpoints/epoch\=43499-step\=43500.ckpt"
# VAE_CHECKPOINT="/home/scur0096/outputs/ego_small_VQVAE_32code_hyp64_euc0_decode_pairwise_interactiondecode_c1.0-ego_small/VAE/2026-05-12/09-35-38/hypeflow-ego_small_VQVAE_32code_hyp64_euc0_decode_pairwise_interactiondecode_c1.0/aagqgkwu/checkpoints/epoch=43499-step=43500.ckpt"
VAE_CHECKPOINT="/home/scur0096/outputs/ego_small_VQVAE_32code_hyp64_euc0_decode_pairwise_interactiondecode_c1.0-ego_small/VAE/2026-05-09/14-48-45/checkpoints/ego_small_VQVAE_32code_hyp64_euc0_decode_pairwise_interactiondecode_c1.0/last-v1.ckpt"

# 3. Execution
time python src/train_flow.py \
  +experiment=ego_small_hyp \
  dataset=ego_small \
  loss=VQVAE \
  model.hyp_channels=64 \
  model.latent_channels=64 \
  loss.codebook_size=32 \
  model.euc_channels=0 \
  general.wandb=disabled \
  flow_train.VAE_checkpoint=${VAE_CHECKPOINT} \
  general.wandb="${WANDB_LOG_MODE}" \
  flow_train.integrate.num_steps=10


  # flow_train.integrate.method=use_flow_map
  # flow_train.VAE_checkpoint=/home/scur0096/outputs/ego_small_VQVAE_32code_hyp64_euc0_decode_pairwise_interactiondecode_c1.0-ego_small/VAE/2026-05-12/09-35-38/hypeflow-ego_small_VQVAE_32code_hyp64_euc0_decode_pairwise_interactiondecode_c1.0/aagqgkwu/checkpoints/epoch=43499-step=43500.ckpt\

  # flow_train.VAE_checkpoint_path=${VAE_CHECKPOINT} \



  