#!/bin/bash
#SBATCH --job-name=qm9_flow
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=24:00:00
#SBATCH --output=outputs/qm9_flow%j.out
#SBATCH --error=outputs/qm9_flow%j.err

# 1. Environment
module load 2024
module load Miniconda3/24.7.1-0
module load Mamba/24.9.0-0
source activate ~/.conda/envs/ggball
export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/src/models/hyperbolic_nn_plusplus

# 2. WandB Setup
export WANDB_START_METHOD=thread
export WANDB_SILENT=true
if [ -f "wandb.key" ]; then
    export WANDB_API_KEY=$(cat wandb.key)
    export WANDB_MODE=online
    WANDB_LOG_MODE=online
    echo "WandB API key loaded from wandb.key"
elif [ -n "$WANDB_API_KEY" ]; then
    export WANDB_MODE=online
    WANDB_LOG_MODE=online
    echo "WandB API key found in environment"
else
    export WANDB_MODE=offline
    WANDB_LOG_MODE=offline
    echo "No WandB API key found. Using offline mode."
fi

# 3. Execution
time ~/.conda/envs/ggball/bin/python3 src/train_flow.py \
  +experiment=qm9 \
  dataset=qm9 \
  loss=VQVAE \
  model.c=${CURVATURE} \
  general.wandb=${WANDB_LOG_MODE} \
  dataset.debug=false \
  flow_train.VAE_checkpoint=${VAE_CHECKPOINT}