#!/bin/bash
#SBATCH --job-name=qm9_hyp_vqvae
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --array=0-4
#SBATCH --output=outputs/qm9_vqvae_%A_%a.out
#SBATCH --error=outputs/qm9_vqvae_%A_%a.err

# 1. Environment
module purge
module load 2024
module load Miniconda3/24.7.1-0
module load Mamba/24.9.0-0

source activate HypeFlow
export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/src/models/hyperbolic_nn_plusplus

# 2. WandB Fixes
export WANDB_START_METHOD=thread
export WANDB_SILENT=true
export WANDB_API_KEY="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"
if [ -n "${WANDB_API_KEY}" ]; then
  export WANDB_MODE=online
  WANDB_LOG_MODE=online
  echo "WANDB_API_KEY detected: using online mode."
else
  export WANDB_MODE=offline
  WANDB_LOG_MODE=offline
  echo "WANDB_API_KEY not set: using offline mode."
fi

# 3. Curvature sweep
CURVATURES=(0.1 0.5 1.0 2.5 5.0)
CURVATURE=${CURVATURES[$SLURM_ARRAY_TASK_ID]}
echo "Array task ${SLURM_ARRAY_TASK_ID} / curvature ${CURVATURE}"
#sleep $((SLURM_ARRAY_TASK_ID * 30))

# 4. Execution
time python3 src/main.py \
   +experiment=qm9 \
   dataset=qm9 \
   loss=VQVAE \
   model.c=${CURVATURE} \
   model.k_in=${CURVATURE} \
   model.k_hidden=${CURVATURE} \
   model.k_out=${CURVATURE} \
   model.k_poin_out=$(awk "BEGIN {print 1/${CURVATURE}}") \
   general.wandb=${WANDB_LOG_MODE} \
   dataset.debug=false \
   model.hyp_channels=64 \
   model.latent_channels=64 \
   model.euc_channels=0 \
   loss.codebook_size=32 \
   loss.lambda_commitment_weight=2.0 \
   loss.lambda_vq_loss_weight=0.0 \
   loss.use_riemannian_optimizer=True \
   loss.lambda_l2=0.01 \
   loss.lambda_euc2node=0 \
   loss.lambda_euc2edge=0 \
   loss.lambda_hyp2node=5 \
   loss.lambda_hyp2edge=5 \
   train.batch_size=32 \
   train.n_epochs=30000 \
   train.lr_scheduler.T_max=30000 \
   loss.use_kmeans=True \
   model.sample_codebook_temp=0.1 \
   loss.lambda_orthogonal_reg_weight=0.3
