#!/bin/bash
#SBATCH --job-name=setup_env
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=03:00:00
#SBATCH --output=outputs/setup_env%j.out
#SBATCH --error=outputs/setup_env%j.err

# 1. Environment
module purge
module load 2024
module load Miniconda3/24.7.1-0
module load Mamba/24.9.0-0

conda env create -f environment.yml
source activate HypeFlow
pip install --find-links https://data.pyg.org/whl/torch-2.1.0+cu118.html pyg_lib